services:
  - type: web
    name: textarena-fullstack-demo
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install .
    startCommand: python -m uvicorn examples.fullstack_demo.backend.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FULLSTACK_DEMO_RELOAD
        value: "0"
      - key: PYTHON_VERSION
        value: "3.10.0"

