name: ✨ Feature Request
description: Suggest a new game or feature for TextArena.
title: "[Feature Request] "
labels: [enhancement]
body:
  - type: checkboxes
    id: steps
    attributes:
      label: Required prerequisites
      description: Make sure you've completed the following steps before submitting your issue -- thank you!
      options:
        - label: I have searched the [Issue Tracker](https://github.com/LeonGuertler/TextArena/issues) that this hasn't already been reported. (comment there if it has.)
          required: true
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature type
      description: What type of feature are you proposing?
      options:
        - New game
        - Enhancement to existing game
        - Platform/infrastructure improvement
        - UI/UX improvement
        - Documentation improvement
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: game-name
    attributes:
      label: Game name (if applicable)
      description: If this request is for an existing game, please enter the exact name of the game.
      placeholder: e.g., Chess, TicTacToe, SpellingBee, etc.
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a concise summary of the feature request.
      value: |
        # [Feature Name]
        ## Summary
        <!-- Brief overview of the proposed feature -->
    validations:
      required: true
  - type: textarea
    id: game-description
    attributes:
      label: Game/Feature Description
      description: If proposing a new game, describe how it works. For other features, describe the functionality in detail.
      value: |
        ## Game Description
        <!-- Detailed description of the game mechanics or feature functionality -->

        ## Game Rules
        ### 1. Setup
        <!-- How the game is initialized -->

        ### 2. Gameplay
        <!-- How the game is played -->

        ### 3. Winning
        <!-- Win conditions and scoring -->
      render: markdown
  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Describe any technical aspects to consider for implementation.
      value: |
        ## Technical Details
        <!-- Implementation details, algorithms, or data structures to consider -->

        ## Integration
        <!-- How this feature would integrate with the existing platform -->
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches or implementations?
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, examples, or mockups about the feature request here.
